### ISSUE TITLE
Haptics example not working

### ISSUE THREAD

**Issue by klyap** [supermedium/superframe#313]
1. The sample page gives me this error "Connection timed out Error code 522": https://supermedium.com/superframe/components/haptics/
2. The code sample also doesn't work for me, even after I updated AFrame version to 1.4.1
[running the code in Glitch](https://glitch.com/edit/#!/aged-educated-gallium?path=examples%2Fhaptics.html%3A5%3A0) gives me console errors:
```
hand-controls.js:198 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'charAt')
    at n.update (hand-controls.js:198:59)
    at n.initComponent (component.js:333:10)
    at n.updateProperties (component.js:305:12)
    at e.exports.Component (component.js:81:8)
    at new n (component.js:665:15)
    at d.initComponent (a-entity.js:319:17)
    at d.updateComponent (a-entity.js:471:10)
    at d.updateComponents (a-entity.js:442:12)
    at a-entity.js:243:12
    at a-node.js:143:17
    ```

**Comment by diarmidmackenzie** [comment]
Not sure what's going on with the hosted examples at supermedium.com.

In terms of your glitch, the code for this example is out of date (not updated since A-Frame 0.7.0 !)

The[ schema for hand-controls](https://aframe.io/docs/1.4.0/components/hand-controls.html) has changed, so instead of 
        hand-controls="left"

you need:
        hand-controls="hand:left"
        
That's the cause of the error.
Remixed clitch with this fixed is here:
https://obvious-scratched-harmonica.glitch.me/haptics.html

I don't have time just now to test in VR, so not sure if that's the only problem, but hopefully you can test with this glitch & update this issue with your findings.

**Comment by klyap** [comment]
Just tested the Glitch on a headset and verified that it works! Here's a PR to fix the haptics example: https://github.com/supermedium/superframe/pull/314

Also heads up I'm seeing `hand-controls="left"` in a couple other examples/scenes in this repo.
