### ISSUE TITLE
[template] case mustache return handlebars compiler

### ISSUE THREAD

**Issue by isaac-pj** [supermedium/superframe#329]
The package aframe-template-component in **npm** version **3.2.1**

When i try to render mustache template an error is throwed out on console.

```error
mustache.min.js:1 Uncaught (in promise) TypeError: Invalid template! Template should be a "string" but "function" was given as the first argument for mustache#render(template, view, partials)
    at Object.render (mustache.min.js:1:9011)
    at renderTemplate (index.js:109:23)
    at n.renderTemplate (index.js:78:28)
```

checking the `index.js` at line **:184** i see that the case is wrongly returning handlebars compiler for mustache case

``` javascript
    case MUSTACHE: {
      return compileHandlebarsTemplate;
    }
```
I see that the problem was fixed on this commit [4d1a49b](https://github.com/supermedium/superframe/commit/4d1a49bf39d9ab8c1462aca64c22799d18ac81c8) 6 years before, but the package was published in last 3 months and the bug there is.

**Comment by vincentfretin** [comment]
3.2.2 was published https://www.npmjs.com/package/aframe-template-component I guess you can close the issue?
