### ISSUE TITLE
Does not load in A-Frame 1.6.0: getComputedAttribute is not a function

### ISSUE THREAD

**Issue by herebefrogs** [supermedium/superframe#341]
Throw the following error in the JS console:

```
TypeError: e.getComputedAttribute is not a function
    at i (aframe-layout-component@3.0.1:1:1702)
    at aframe-layout-component@3.0.1:1:1793
    at Array.forEach (<anonymous>)
    at n.init (aframe-layout-component@3.0.1:1:1661)
    at n.initComponent (component.js:253:10)
    at n.updateProperties (component.js:239:12)
    at e.exports.Component (component.js:107:8)
    at new n (component.js:674:15)
    at u.initComponent (a-entity.js:302:17)
    at u.updateComponent (a-entity.js:458:10)
```

Example: https://glitch.com/edit/#!/glory-pear-asp?path=index.html%3A1%3A0

**Comment by vincentfretin** [comment]
Please test latest versions. The error is coming from aframe-layout-component@3.0.1
We are currently on version 5.3.0 https://www.npmjs.com/package/aframe-layout-component

**Comment by herebefrogs** [comment]
My bad, the newer version works. I got this example from A-Frame School whose examples are all outdated.

**Comment by vincentfretin** [comment]
I did https://github.com/aframevr/aframe/pull/5567 to update some urls.
